
// import type { Metadata } from "next";
// import { GeistSans, GeistMono } from "geist/font"; // <-- توجه به نام صحیح
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
//       <body className="font-sans antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'سامانه مدیریت چارت‌های تحصیلی',
  description: 'سیستم مدیریت چارت‌های درسی دانشگاه',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl" className={inter.className}>
      <body className="font-sans antialiased bg-gray-50">
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}